import Head from 'next/head'
import Footer from '../components/Footer';
import dynamic from 'next/dynamic';
import React from "react";
import { Alert } from '../components/alert.jsx';
import { FaPlusSquare, FaBell, FaDollarSign, FaHeadphonesAlt } from "react-icons/fa";
import Link from "next/link"
import Image from 'next/image'

const Header = dynamic(() => import('../components/Header'), {
  ssr: false,
})

const Sender = dynamic(() => import('../components/Send'), {
  ssr: false,
})

export default function Home() {
  return (
    <div className="min-h-screen" data-theme="cupcake">
      <Head>
        <title>digital ticket stream startup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Alert />

      <div className="w-full min-h-screen">

          <div className="m-auto w-1/2">
            <Sender />
          </div>

      </div>

      <Footer />
    </div >
  )
}
